// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var View = require("../src/View.js");

Jest.describe("", (function (param) {
        return Jest.test("", (function (param) {
                      return Jest.Expect.toEqual("py-1.5", Jest.Expect.expect(View.header));
                    }));
      }));

/*  Not a pure module */
