// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.js");
var View = require("../src/View.js");

Jest.describe("", (function () {
        Jest.test("", (function () {
                return Jest.Expect.toEqual(Jest.Expect.expect(View.header), "py-1.5");
              }));
        Jest.test("content", (function () {
                return Jest.Expect.toEqual(Jest.Expect.expect(View.header10), "before:content-['']");
              }));
        Jest.test("self & children selector", (function () {
                return Jest.Expect.toEqual(Jest.Expect.expect(View.header11), "peer-checked:[&>svg]:rotate-180");
              }));
        Jest.test("descendant combinator", (function () {
                return Jest.Expect.toEqual(Jest.Expect.expect(View.header12), "[&_a]:tw-mt-4");
              }));
      }));

/*  Not a pure module */
