// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var header = "py-1.5";

var header2 = "divide-y";

var header3 = "xl:min-w-1/5";

var header4 = "focus:outline-none";

var header5 = "w-[100%]";

var header6 = "w-[calc(100%-40px)]";

var header7 = "translate-x-[calc(-50%+27px)]";

var header8 = "!pb-[270px]";

var header9 = "translate-x-2/4";

var header10 = "before:content-['']";

var header11 = "peer-checked:[&>svg]:rotate-180";

var header12 = "[&_a]:tw-mt-4";

exports.header = header;
exports.header2 = header2;
exports.header3 = header3;
exports.header4 = header4;
exports.header5 = header5;
exports.header6 = header6;
exports.header7 = header7;
exports.header8 = header8;
exports.header9 = header9;
exports.header10 = header10;
exports.header11 = header11;
exports.header12 = header12;
/* No side effect */
