let header = %twc("py-1.5")
let header2 = %twc("divide-y")
let header3 = %twc("xl:min-w-1/5")
let header4 = %twc("focus:outline-none")
let header5 = %twc("w-[100%]")
let header6 = %twc("w-[calc(100%-40px)]")
let header7 = %twc("translate-x-[calc(-50%+27px)]")
let header9 = %twc("translate-x-2/4")
